import { cloudinaryBucketName } from "../constants";

export enum Enviornments {
  local,
  dev,
  stage,
  production,
}

const homeIp = "192.168.0.103";
const pgIp = "192.168.29.9";
const deviFaiIp = "192.168.1.142";
// need to change ip
export const URLs = {
  [Enviornments.local]: {
    apiURL: "http://192.168.1.142:8001/good_luck/api/v1",
    socketURL: "http://192.168.1.142:8001/",
  },
  [Enviornments.dev]: {
    apiURL: "http://10.252.215.38:8001/good_luck/api/v1",
    socketURL: "http://10.252.215.38:8001",
  },
  [Enviornments.stage]: {
    apiURL: "http://10.252.215.38:8001/good_luck/api/v1",
    socketURL: "http://10.252.215.38:8001",
  },
  [Enviornments.production]: {
    apiURL: "https://goodluckserver.in/good_luck/api/v1",
    socketURL: "https://goodluckserver.in/",
  },
};

export const cloudinaryURL = `https://api.cloudinary.com/v1_1/${cloudinaryBucketName}/image/upload`;

export const endPoints = {
  getOTP: "/auth/login",
  resendOTP: "/auth/resend_otp",
  verifyOTP: "/auth/loginVerifyotp",
  addNewUser: "/auth/newUserRequest",
  newUserVerifyOTP: "/auth/authRequestVerifyotp",
  deleteUser: "/auth/delete-profile",
  getTranstactionHistory: "/auth/transaction-history",
  updateProfile: "/auth/update-profile",
  matrimonySubscribe: "/auth/matrimony-subscription/buy",
  datingSubscribe: "/auth/dating-subscription/buy",
  validatePromoCode: "/auth/check-promo-code",
  withDrawRequest: "/withdraw/create",

  categoryList: "/productCategory",
  addCategory: "/productCategory/createProductCategory",
  productList: "/product",
  productListByCategory: "/product/filter",
  productDetailsById: "/product",
  addProduct: "/product",
  createOrder: "/order/createOrder",
  allOrderList: "/order",
  orderList: "/order/user",
  orderDetails: "/order",

  createRazorPayorder: "/pay/orders",
  payment: "/pay",

  getAllMatrimonyProfile: "/matrimony/getAll",
  getMatrimonyProfileById: "/matrimony",
  createMatrimonyProfile: "/matrimony/createMatrimonyProfile",
  updateMatrimonyProfile: "/matrimony/update",
  getTopFiveBrideProfile: "/matrimony/brides",
  getTopFiveGroomProfile: "/matrimony/grooms",
  getMatrimonyPlans: "/matrimony/subscription/get",

  getAllDatingProfile: "/dating/getAll",
  getDatingProfileById: "/dating",
  createDatingProfile: "/dating/createDatingProfile",
  updateDatingProfile: "/dating/update",
  getMatrimonySentLikes: "/matrimony/get/sent_like",
  getMatrimonyReceivedLikes: "/matrimony/get/pending_like",
  sendMatrimonyLike: "/matrimony/send_like",
  getDatingSentLikes: "/dating/sent_like",
  getDatingRecivedLikes: "/dating/pending_like",
  sendDatingLike: "/dating/send_like",
  createChatRoomByProfileId: "/datingChat/create",
  getAllMessagesByMatchesID: "/datingChat/messages",
  getAllMatches: "/matchedProfile/matches",
  getDatingPlans: "/dating/subscription/get",

  getAllAstrologer: "/astrologer",
  getFilteredAsrologer: "/astrologer/category/filter",
  getAstrologerById: "/astrologer",
  getWalletBalance: "/auth/wallet-balance",
  getAstroWalletBalance: "/astrologer/wallet-balance",
  addMoneyInWallet: "/auth/userWallet/addBalance",
  addMoneyByAstrologerId: "/astrologer/astroWallet/addBalance",
  getAllAstrologerChat: "/astrologerChat/chat-history",
  createAstrologer: "/astrologer/createAstrologerRequest",
  updateAstrologer: "/astrologer/updateRequest",
  updateProfileOTP: "/astrologer/verifyOTPandUpdate",
  postReviewRatingForAstrologer: "/astrologer/post-review",
  getReviewRatingForAstrologer: "/astrologer/getall-reviews",
  getAstrologerAllCategory: "/astrologer/category/getAll",
  getAstrologerTransactionHistory: "/astrologer/transaction-history",
  toogleAstrologerState: "/astrologer/toggle",

  createHomeAndLandBannerPost: "/homeLandBanner/create",
  getAllHomeAndLandBannerPost: "/homeLandBanner/getAll",
  getAllHomeAndLandBannerPostById: "/homeLandBanner/getByUserId",
  getAllHomeAndLandBannerPostByType: "/homeLandBanner/getByCategory",
  getHomeAndLandBannerDetailsById: "",
  updateHomeAndLandBannerPost: "/homeLandBanner/update",
  deleteHomeAndLandBannerPost: "/homeLandBanner/delete",

  createHomeAndLandTextPost: "/homeLandText/create",
  getAllHomeAndLandTextPost: "/homeLandText/getAll",
  getAllHomeAndLandTextPostById: "/homeLandText/getByUserId",
  getHomeAndLandTextDetailsById: "",
  updateHomeAndLandTextPost: "/homeLandText/update",
  deleteHomeAndLandTextPost: "/homeLandText/delete",
  getAllHomeAndLandTextPostByType: "/homeLandText/getByCategory",

  createJobBannerPost: "/jobBanner/create",
  getAllJobBannerPost: "/jobBanner/getAll",
  getAllJobBannerPostById: "/jobBanner/getByUserId",
  getJobBannerDetailsById: "",
  updateJobBannerPost: "/jobBanner/update",
  deleteJobBannerPost: "/jobBanner/delete",
  getAllJobBannerPostByType: "/jobBanner/getJobBannerAdsByCategory",

  createJobTextPost: "/jobText/create",
  getAllJobTextPost: "/jobText",
  getAllJobTextPostById: "/jobText",
  getJobTextDetailsById: "",
  updateJobTextPost: "/jobText/update",
  deleteJobTextPost: "/jobText/delete",
  getAllJobTextPostByType: "/jobText/getAllJobTextAdsByCategory",

  subscribeForAdvertisement: "/auth/ads-subscription/buy",
  getAllsubscribtionForads: "/advertisement/get",

  getAstrologerChatDetailsByUserAndAstrologerId: "/astrologerChat/chat-history",
  getAstrologerChatList: "/astrologerChat/chat-list",

  createKundaliRequest: "/janamKundli/create",
  createMatchMaking: "/mariageMaking/create",

  getPanchangByDate: "/panchang/getByDate",
  rashiFalGetByDate: "/rasifal/getByDate",
  calenderGetAll: "/calender/getAll",
  dakshinaGetAll: "/dakshina/getAll",
  getLiveTV: "/liveTv/getAll",
  postDakshinaPayment: "/dakshina/payment",

  getAllLocalServiceCategory: "/localCategory/getAll",
  getAllLocalServiceByCategory: "/localService/category",
  createLocalService: "/localService",
  subscribeForLocalService: "/auth/local-subscription/buy",
  getLocalServicePlans: "/local/subscription/get",
  filterLocalService: "/localService/filter",

  getDashboardAds: "/admin-ads",

  getCalenderEventsByType: "/calender-event/type",
};
export const enviornment = Enviornments.local;
export const indianStatesAndCities = [
  {
    state: "Andhra Pradesh",
    cities: [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Tirupati",
      "Rajahmundry",
      "Kurnool",
      "Kadapa",
      "Anantapur",
      "Eluru",
    ],
  },
  {
    state: "Arunachal Pradesh",
    cities: [
      "Itanagar",
      "Tawang",
      "Ziro",
      "Pasighat",
      "Bomdila",
      "Naharlagun",
      "Aalo",
      "Seppa",
      "Khonsa",
      "Tezu",
    ],
  },
  {
    state: "Assam",
    cities: [
      "Guwahati",
      "Dibrugarh",
      "Silchar",
      "Jorhat",
      "Tezpur",
      "Tinsukia",
      "Nagaon",
      "Bongaigaon",
      "Diphu",
      "Sivasagar",
    ],
  },
  {
    state: "Bihar",
    cities: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Darbhanga",
      "Purnia",
      "Arrah",
      "Begusarai",
      "Katihar",
      "Munger",
    ],
  },
  {
    state: "Chhattisgarh",
    cities: [
      "Raipur",
      "Bilaspur",
      "Durg",
      "Bhilai",
      "Korba",
      "Rajnandgaon",
      "Jagdalpur",
      "Raigarh",
      "Ambikapur",
      "Mahasamund",
    ],
  },
  {
    state: "Goa",
    cities: [
      "Panaji",
      "Margao",
      "Vasco da Gama",
      "Mapusa",
      "Ponda",
      "Bicholim",
      "Curchorem",
      "Canacona",
      "Quepem",
      "Sanguem",
    ],
  },
  {
    state: "Gujarat",
    cities: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Junagadh",
      "Gandhinagar",
      "Anand",
      "Nadiad",
    ],
  },
  {
    state: "Haryana",
    cities: [
      "Gurugram",
      "Faridabad",
      "Panipat",
      "Ambala",
      "Karnal",
      "Yamunanagar",
      "Hisar",
      "Rohtak",
      "Sonipat",
      "Panchkula",
    ],
  },
  {
    state: "Himachal Pradesh",
    cities: [
      "Shimla",
      "Manali",
      "Dharamshala",
      "Solan",
      "Mandi",
      "Hamirpur",
      "Kullu",
      "Una",
      "Bilaspur",
      "Nahan",
    ],
  },
  {
    state: "Jharkhand",
    cities: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Deoghar",
      "Hazaribagh",
      "Giridih",
      "Ramgarh",
      "Phusro",
      "Chakradharpur",
    ],
  },
  {
    state: "Karnataka",
    cities: [
      "Bengaluru",
      "Mysuru",
      "Mangaluru",
      "Hubballi",
      "Belagavi",
      "Davangere",
      "Shivamogga",
      "Tumakuru",
      "Ballari",
      "Vijayapura",
    ],
  },
  {
    state: "Kerala",
    cities: [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Thrissur",
      "Kollam",
      "Kannur",
      "Palakkad",
      "Kottayam",
      "Alappuzha",
      "Malappuram",
    ],
  },
  {
    state: "Madhya Pradesh",
    cities: [
      "Bhopal",
      "Indore",
      "Gwalior",
      "Jabalpur",
      "Ujjain",
      "Sagar",
      "Satna",
      "Rewa",
      "Ratlam",
      "Dewas",
    ],
  },
  {
    state: "Maharashtra",
    cities: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Nashik",
      "Aurangabad",
      "Solapur",
      "Thane",
      "Kolhapur",
      "Amravati",
      "Sangli",
    ],
  },
  {
    state: "Manipur",
    cities: [
      "Imphal",
      "Thoubal",
      "Bishnupur",
      "Churachandpur",
      "Kakching",
      "Ukhrul",
      "Tamenglong",
      "Senapati",
      "Jiribam",
      "Moirang",
    ],
  },
  {
    state: "Meghalaya",
    cities: [
      "Shillong",
      "Tura",
      "Nongpoh",
      "Jowai",
      "Baghmara",
      "Williamnagar",
      "Mairang",
      "Nongstoin",
      "Mawkyrwat",
      "Cherrapunjee",
    ],
  },
  {
    state: "Mizoram",
    cities: [
      "Aizawl",
      "Lunglei",
      "Champhai",
      "Serchhip",
      "Kolasib",
      "Lawngtlai",
      "Mamit",
      "Siaha",
      "Bairabi",
      "Vairengte",
    ],
  },
  {
    state: "Nagaland",
    cities: [
      "Kohima",
      "Dimapur",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Zunheboto",
      "Phek",
      "Mon",
      "Longleng",
      "Kiphire",
    ],
  },
  {
    state: "Odisha",
    cities: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Sambalpur",
      "Puri",
      "Balasore",
      "Baripada",
      "Berhampur",
      "Bhadrak",
      "Angul",
    ],
  },
  {
    state: "Punjab",
    cities: [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Hoshiarpur",
      "Mohali",
      "Pathankot",
      "Moga",
      "Barnala",
    ],
  },
  {
    state: "Rajasthan",
    cities: [
      "Jaipur",
      "Jodhpur",
      "Udaipur",
      "Kota",
      "Ajmer",
      "Bikaner",
      "Alwar",
      "Bhilwara",
      "Pali",
      "Sikar",
    ],
  },
  {
    state: "Sikkim",
    cities: [
      "Gangtok",
      "Namchi",
      "Gyalshing",
      "Mangan",
      "Rangpo",
      "Singtam",
      "Chungthang",
      "Jorethang",
      "Soreng",
      "Ravangla",
    ],
  },
  {
    state: "Tamil Nadu",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tirunelveli",
      "Vellore",
      "Erode",
      "Thoothukudi",
      "Dindigul",
    ],
  },
  {
    state: "Telangana",
    cities: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Karimnagar",
      "Ramagundam",
      "Khammam",
      "Mahbubnagar",
      "Suryapet",
      "Miryalaguda",
      "Jagtial",
    ],
  },
  {
    state: "Tripura",
    cities: [
      "Agartala",
      "Udaipur",
      "Dharmanagar",
      "Kailashahar",
      "Ambassa",
      "Belonia",
      "Khowai",
      "Sonamura",
      "Melaghar",
      "Amarpur",
    ],
  },
  {
    state: "Uttar Pradesh",
    cities: [
      "Lucknow",
      "Kanpur",
      "Varanasi",
      "Agra",
      "Prayagraj",
      "Meerut",
      "Ghaziabad",
      "Bareilly",
      "Aligarh",
      "Moradabad",
    ],
  },
  {
    state: "Uttarakhand",
    cities: [
      "Dehradun",
      "Haridwar",
      "Roorkee",
      "Haldwani",
      "Rudrapur",
      "Kashipur",
      "Nainital",
      "Pithoragarh",
      "Almora",
      "Bageshwar",
    ],
  },
  {
    state: "West Bengal",
    cities: [
      "Kolkata",
      "Howrah",
      "Darjeeling",
      "Siliguri",
      "Durgapur",
      "Asansol",
      "Malda",
      "Kharagpur",
      "Jalpaiguri",
      "Haldia",
    ],
  },
  {
    state: "Andaman and Nicobar Islands",
    cities: [
      "Port Blair",
      "Rangat",
      "Diglipur",
      "Mayabunder",
      "Car Nicobar",
      "Campbell Bay",
      "Kamorta",
      "Nancowry",
      "Little Andaman",
      "Neil Island",
    ],
  },
  {
    state: "Chandigarh",
    cities: ["Chandigarh"],
  },
  {
    state: "Dadra and Nagar Haveli and Daman and Diu",
    cities: [
      "Silvassa",
      "Daman",
      "Diu",
      "Amli",
      "Samarvarni",
      "Vapi",
      "Kachigam",
      "Bhimpore",
      "Kadaiya",
      "Dabhel",
    ],
  },
  {
    state: "Lakshadweep",
    cities: [
      "Kavaratti",
      "Agatti",
      "Amini",
      "Andrott",
      "Kalpeni",
      "Kadmat",
      "Minicoy",
      "Chetlat",
      "Bitra",
      "Bangaram",
    ],
  },
  {
    state: "Delhi",
    cities: [
      "New Delhi",
      "Delhi",
      "Narela",
      "Dwarka",
      "Saket",
      "Rohini",
      "Janakpuri",
      "Vasant Kunj",
      "Karol Bagh",
      "Connaught Place",
    ],
  },
  {
    state: "Puducherry",
    cities: [
      "Puducherry",
      "Karaikal",
      "Mahe",
      "Yanam",
      "Ousteri",
      "Villiyanur",
      "Thirukkanur",
      "Bahour",
      "Ariyankuppam",
      "Madagadipet",
    ],
  },
];

export const interests = [
  "badminton",
  "football",
  "cricket",
  "makeUp",
  "dance",
  "yoga",
  "meditation",
  "swimming",
  "movie",
  "party",
];

export const states = indianStatesAndCities.map((item: any) => item?.state);

export interface IProfileDetails {
  name?: string;
  state?: string;
  city?: string;
  pin?: string;
  education?: string;
  age?: string;
  caste?: string;
  salary?: string;
  whatsappno?: string;
  fblink?: string;
  bio?: string;
}

export const religions = ["hindu", "muslim", "others"];
export const education = [
  "bachelors",
  "in college",
  "high school",
  "phd",
  "in Grad school",
  "masters",
  "trade school",
];

export const languages = ["Bengali", "English", "Hindi", "Tamil", "Telugu"];

export enum ProfileType {
  own,
  matrimony,
  dating,
}
