export const SOCKET_TYPES = {
  registerUser: "register_user",
  chatResponse: "chat-response",
  chatAccepted: "chat-accepted",
  chatRejected: "chat-rejected",
  chatRequested: "chat-request",
  chatRequestFromUser: "chat-request-from-user",
  receivedMessage: "received-message",
  chatError: "chat-error",
  chatEnd: "chat-end",
  endChat: "end-chat",
  sendMessage: "send-message",
  pauseChat: "pause-chat",
  resumeChat: "resume-chat",
  chatPaused: "chat-paused",
  chatResumes: "chat-resumed",
  joinRoom: "join-room",
  registerAstrologer: "register_astrologer",
  datingNewMessage: "new_message",
  datingSendMessage: "send_message",

  callRequest: "call-request",
  callResponse: "call-response",
  endCall: "end-call",
  callEnd: "call-end",
  callError: "call-error",
  callRequestFromUser: "call-request-from-user",
  callDetails: "call-details",
  joinCall: "call-accepted",
  callRejected: "call-rejected",
};
